ods rtf file='C:\Users\rifa\Documents\SAS_Clinical\Project\migrane.rtf';
options nodate nonumber;
title1 color=bio bcolor=antiquewhite Report Generated By Rifat Jahan;
footnote color=bio bcolor=antiquewhite "On %sysfunc(date(),date9.)";

libname rifat 'C:\Users\rifa\Documents\SAS_Clinical\Project';

title2 c=blue f=b h=3 Migraine Attack Data Analyses;
title3 c=bippk h=2 f=b DEMOGRAPHICS OF PATIENTS;

title2 color=bippk f=bold bcolor=antiquewhite h=3 Table1. Average age of patients by gender;
proc sql;
select sex label='Gender', count(Ptid) as N, avg(Age)as MeanAge
from rifat.ptinfo
group by sex;
quit; 

*Or by using proc tabulate;

proc tabulate data=rifat.ptinfo;
class sex;
var Age;
table sex='', Age=''*(N mean= 'Mean Age')/box='Gender';
run; 

/*proc print data=rifat.pthistory; run;*/

title2 c=brown f=b bcolor=ltgray h=2 "Table 2. Analysis of smoking and Alcohol";
*creating format;
proc format;
	value $yesno
			'Y' = 'Yes'
			'N' = 'No'
			; 
proc tabulate data=rifat.pthistory;
class smoking alcohol;
table (smoking alcohol)* n='';
format Smoking Alcohol $yesno.;
run;

title2 c=blue h=2 "Table 3. Analysis of smoking history and Alcohol consumption";
proc means data=rifat.pthistory N Mean Stddev;
var smkyncig smkyyears alcyndpw;
label smkyncig = 'No. of Cigars Smoked'
	  smkyyears = 'No. of Years Smoked'
	  alcyndpw = 'No. of Drinks Per Week';
run;


title2 c=blue bcolor=bisque f=b	h=4 underlin=3 'VISIT 1';
 title3 c=bippk bcolor=antiquewhite f=b h=3 underlin= 2 ANALYSIS of CLINICAL EXAMINATION;
/*dataset for visit=1*/
 data rifat.ClinicExviv1_visit1;
 	set rifat.ClinicExviv1;
	where Visit=1;
run;

title2 c=bippk bcolor=ltgray f=b underlin=1 h=2 "Table 4. Means of Blood Pressure and Pulse Rate";
 proc means data=rifat.ClinicExviv1_visit1  N Mean StdDev;
 var Pulse Bpsystolic Bpdiastolic;
 label Bpsystolic = 'Systolic Blood Pressure'
 	   Bpdiastolic = 'Diastolic Blood Pressure';
 run;

title2 c=blueviolet bcolor=antiquewhite f=b h=2 "Table 5. Summary of Other Diseases";
footnote c=blue f=b h=2 "Note: No patients were found with Angina, Myoinfa, Allergy and Cerinc.";
 proc tabulate data=rifat.ClinicExviv1_visit1;
class Cardio Respiratory Abdomen Cns;
CLASSLEV Cardio Respiratory Abdomen Cns/S=[just=c];
tables (Cardio={s=[background=pink just=c]} 
		Respiratory={s=[background=yellow just=c]} 
		Abdomen={s=[background=orange just=c]}
		Cns={s=[background=aquamarine just=c]}), 
		n={label='N' s=[background=bio]} pctn={label='Percent' s=[background=bio]};
run;

title2 c=blue f=b underlin=3 h=4 "LAB TESTING";
title3 c=blue f=b h=2 Table 6. Analysis of Patient Blood History Data;
footnote;
proc means data=rifat.labtest N Mean Stddev;
var Sc Hg Urea Wbc Sodium Neutrophils Eosinophils Basophils Potassium Lymphocytes
	Sugar Monocytes Platelets Sb Sgot Sgpt;
run;

title2 c=blue f=b h=2 "Table 7. Summary of Urine Analysis, Pregnancy and ECG";
*craete format;
	proc format;
		value $nnawnl
				'N' = 'Normal'
				'WNL' = 'Within Normal Limits'
				'Ne' = 'Negative'
				'NA' = 'Not Applicable'
				;
proc tabulate data=rifat.labtest;
class Urineanalysis Urinepregnancy Ecg;
CLASSLEV Urineanalysis Urinepregnancy Ecg/S=[just=c];
tables(Urineanalysis={label='Urine Analysis' s=[background=pink just=l]} 
	  Urinepregnancy={label='Pregnancy' s=[background=yellow just=l]} 
	  Ecg={label='ECG' s=[background=orange just=l]}),
	  n={label='N' s=[background=bio]} pctn={label='Percent' s=[background=bio]}/box='Label';
format Urineanalysis Urinepregnancy Ecg $nnawnl.;		
run;

title;
title2 c=blue f=b underlin=3 h=4 "MIGRAINE ATTACK"; 
title3 c=blue f=b h=2 "Table 8. Averages of Time since Initial Attack(Months), Frequency and Duration";
proc means data=rifat.Migraineattack  N MEAN Stddev;
var V1attksincemonths V1attkfreqpm V1durationattk;
label V1attksincemonths = "Time Since Initial Attack (Months)"
	  V1attkfreqpm = "Frequency Of Attack In A Month"
	  V1durationattk = "Duration Of Attack(Hours)";	
run;


title2 c=bio bcolor=bwh h=2 "Table 9. Analysis of Side Effects Due to Migraine Attack";
 proc tabulate data=rifat.Migraineattack;
class V1aura V1nausea V1blurvision V1ptphobia V1pnphobia;
CLASSLEV V1aura V1nausea V1blurvision V1ptphobia V1pnphobia/S=[just=c];
tables (V1aura={label='Aura' s=[background=aquamarine just=c]} 
		V1nausea={label='Nausea' s=[background=aquamarine just=c]} 
		V1blurvision={label='Blurred Vision' s=[background=aquamarine just=c]}
		V1ptphobia={label='Photophobia' s=[background=aquamarine just=c]}
		V1pnphobia={label='Phonophobia' s=[background=aquamarine just=c]}), 
		n={label='N' s=[background=bio]} pctn={label='Percent' s=[background=bio]};
format V1aura V1nausea V1blurvision V1ptphobia V1pnphobia $yesno.;
run;

title2 c=blue f=b h=3 "Table 10. Analysis of patient history based on drug intake for migraine";
proc report data=rifat.pthistory(where=(Drintakecondition='migrane')) nowd;
   columns Drintakecondition Drintakedrug Drintakegeneric Drintakedose Drintakecontinues
           DrintakecontYdose Drintakenperiodofdisc Drintakedur;
   define  Drintakecondition/'Drug Condition' display width=10;
   define  Drintakedrug/'Drug' display width=20;
   define Drintakegeneric/'Generic' display width=30;
   define Drintakedose/'Dose' display width=8;
   define Drintakecontinues/'Continued';
   define DrintakecontYdose/'Dose' width=15;
   define Drintakenperiodofdisc/'Dis-continuation' width=10;
   define Drintakedur/'Duration' width=20;
   run;
/*Table 10*/
 title2 c=blue  h=2 "Table 10. Analysis of Patient History based on Drug Intake for Migraine";
 proc sql;
 select Drintakecondition label='Drug Condition', Drintakedrug label='Drug', 
		Drintakegeneric label='Generic',Drintakedose label='Dose',Drintakecontinues label='Continued',
		DrintakecontYdose label='Dose',Drintakenperiodofdisc label='Dis-continuation',
		Drintakedur label='Duration' 
from rifat.pthistory
where Drintakecondition='migrane';
run;


title2 c=blue h=2 "Table 11. Analysis of patient history based on drug intake for other diseases";
proc report data=rifat.pthistory(where=(Drintakecondition='others')) nowd;
   columns Drintakecondition Drintakedrug Drintakegeneric Drintakedose Drintakecontinues
           DrintakecontYdose Drintakenperiodofdisc Drintakedur;
   define  Drintakecondition/'Drug Condition' display width=10;
   define  Drintakedrug/'Drug' display width=20;
   define Drintakegeneric/'Generic' display width=30;
   define Drintakedose/'Dose' display width=8;
   define Drintakecontinues/'Continued';
   define DrintakecontYdose/'Dose' width=15;
   define Drintakenperiodofdisc/'Dis-continuation' width=10;
   define Drintakedur/'Duration' width=20;
run;

/*Table 11. by using sql*/
title2 c=blue h=2 "Table 11. Analysis of patient history based on drug intake for other diseases";
proc sql;
 select Drintakecondition label='Drug Condition', Drintakedrug label='Drug', 
		Drintakegeneric label='Generic',Drintakedose label='Dose',Drintakecontinues label='Continued',
		DrintakecontYdose label='Dose',Drintakenperiodofdisc label='Dis-continuation',
		Drintakedur label='Duration' 
from rifat.pthistory
where Drintakecondition='others';
run;

/* Dataset for visit-2 */
  data rifat.clinicexviv1_visit2;
  set rifat.clinicexviv1;
  where visit=2;
  run;

  title2 c=blue f=b underlin=3 h=4 "VISIT-2"; 
  title3 c=blue f=b underlin=2 h=3 "ANALYSIS OF CLINICAL-EXAMINATION";
  title4 c=blue h=2 "Table 12. Means of Blood Pressure and Pulse Rate";
   proc means data=rifat.clinicexviv1_visit2 N Mean Stddev;
   var Pulse Bpsystolic Bpdiastolic;
   label Bpsystolic='Systolic Blood Pressure'
   		 Bpdiastolic='Diastolic Blood Pressure';
   run; 
   
   title2 c=blue h=2 'Table 13. Summary of Other Diseases';
   proc tabulate data=rifat.clinicexviv1_visit2;
   class Cardio Respiratory Abdomen Cns;
   CLASSLEV Cardio Respiratory Abdomen Cns/S=[just=c];
   tables (Cardio={s=[background=pink just=c]} 
		Respiratory={s=[background=yellow just=c]} 
		Abdomen={s=[background=orange just=c]}
		Cns={s=[background=aquamarine just=c]}), 
		n={label='N' s=[background=bio]} pctn={label='Percent' s=[background=bio]};
   format Cardio Respiratory Abdomen Cns $nnawnl.;
   run;

   
title2 c=blue underlin=3 h=3 'Evaluation of Time Difference between Migraine Attack Time and Migraine Attack Reported Time, Nausea and Blood Pressure (Table 14 – Table 22)';
/*proc contents data=rifat.ptvisit2;run;*/
data ptvisit_diff;
	set rifat.ptvisit2;
	*Timediff_MAT_MART_sec=Migreporttime-MigpresentAttktime;
	Timediff_MAT_MART_min=intck('minutes',Migreporttime, MigpresentAttktime);
run;

/*Table14-Table22*/
title2 c=blue h=2 f=b'Table 14. Initial Evaluation';
footnote c=blue "MAT – Migraine Attack Time.   MART – Migraine Attack Reported Time";
proc means data=ptvisit_diff N Mean Stddev;
var evanausea Timediff_MAT_MART_min;
label evanausea='Evaluation of Nausea'
	  Timediff_MAT_MART_min='Time Difference between MAT and MART';
run;

/*Table 14*/
data time;
set rifat.ptvisit2;
Difference = intck('minutes',migreporttime, migpresentattktime);
keep evanausea migpresentattktime migreporttime Difference;
run;
proc tabulate data=time;
   	var evanausea Difference;
	 table evanausea = 'Evaluation of Nausea' 
		   Difference = 'Time Difference between MAT and MART',  
		  (n mean std='Std Dev') / box='Label';
run;
footnote;
/*Data preparation for Table15 - Table21*/
proc print data=rifat.ptvisit2;
var EvaltimetypeHrs;
id Dia Sys;*these are highligted columns when you use ID-as statement;
run;
/*proc contents data=rifat.ptvisit2; run;--check EvaltimetypeHrs-is ch or numeric*/

***************Table15 - Table21************************;
title2 c=blue h=2 "Table 15. Evaluation after 30 Minutes";
proc means data=rifat.ptvisit2 N Mean Stddev;
var Sys Dia evanausea;
where EvaltimetypeHrs='0.5hours';
label Dia = 'Diastolic Blood Pressure'
	  Sys = 'Systolic Blood Pressure'
	  evanausea = 'Evaluation of Nausea';
run;

title2 c=blue h=2 "Table 16. Evaluation after 1 hour";
proc means data=rifat.ptvisit2 N Mean Stddev;
var Sys Dia evanausea;
where EvaltimetypeHrs='1hours';
label Dia = 'Diastolic Blood Pressure'
	  Sys = 'Systolic Blood Pressure'
	  evanausea = 'Evaluation of Nausea';
run;

title2 c=blue h=2 "Table 17. Evaluation after 2 hours";
proc means data=rifat.ptvisit2 N Mean Stddev;
var Sys Dia evanausea;
where EvaltimetypeHrs='2hours';
label Dia = 'Diastolic Blood Pressure'
	  Sys = 'Systolic Blood Pressure'
	  evanausea = 'Evaluation of Nausea';
run;

title2 c=blue h=2 "Table 18. Evaluation after 3 hours";
proc means data=rifat.ptvisit2 N Mean Stddev;
var Sys Dia evanausea;
where EvaltimetypeHrs='3hours';
label Dia = 'Diastolic Blood Pressure'
	  Sys = 'Systolic Blood Pressure'
	  evanausea = 'Evaluation of Nausea';
run;

title2 c=blue h=2 "Table 19. Evaluation after 4 hours";
proc means data=rifat.ptvisit2 N Mean Stddev;
var Sys Dia evanausea;
where EvaltimetypeHrs='4hours';
label Dia = 'Diastolic Blood Pressure'
	  Sys = 'Systolic Blood Pressure'
	  evanausea = 'Evaluation of Nausea';
run;

title2 c=blue h=2 "Table 20. Evaluation after 6 hours";
proc means data=rifat.ptvisit2 N Mean Stddev;
var Sys Dia; 
where EvaltimetypeHrs='6hours';
label Dia = 'Diastolic Blood Pressure'
	  Sys = 'Systolic Blood Pressure';
run;

title2 c=blue h=2 "Table 21. Evaluation after 6-24 hours";
proc means data=rifat.ptvisit2 N Mean Stddev;
var Sys Dia; 
where EvaltimetypeHrs='6-24hours';
label Dia = 'Diastolic Blood Pressure'
	  Sys = 'Systolic Blood Pressure';
run;


